const assets = {
  images: {
    logo: require("./images/logo.png"),
    logo01: require("./images/logo.png"),
    Avatar:require("./images/Avatar.png"),
    info:require("./images/info.png"),
    sucess:require("./images/sucess.png"),
    icon:require("./images/online-learning.png"), 
    EditButton:require("./images/EditButton.png"), 
    avatar:require("./images/Avatar-def.png"), 
    Image:require("./images/Image.png"), 
    partners01:require("./images/partners/p01.png"),
    partners02:require("./images/partners/p02.png"),
    partners03:require("./images/partners/p03.png"),
    partners04:require("./images/partners/p04.png"),
    partners05:require("./images/partners/p05.png"),
    partners06:require("./images/partners/p06.png"),
    partners07:require("./images/partners/p07.png"),
    partners08:require("./images/partners/p08.png"),
    partners09:require("./images/partners/p09.png"),
    partners10:require("./images/partners/p10.png"),
    partners11:require("./images/partners/p11.png"),
    partners12:require("./images/partners/p12.png"),
    partners13:require("./images/partners/p13.png"),
    partners14:require("./images/partners/p14.png"),
    partners15:require("./images/partners/p15.png"),
    partners16:require("./images/partners/p16.png"),
    partners17:require("./images/partners/p17.png"),
    partners18:require("./images/partners/p18.png"),
    partners20:require("./images/partners/p20.png"),
    partners21:require("./images/partners/p21.png"),
    Coursescertif:require("./images/Courses-certif.png"),
    
    otherProduct01:require("./images/otherProduct01.png"),
    otherProduct02:require("./images/otherProduct02.png"),
    otherProduct03:require("./images/otherProduct03.png"),
    otherProduct04:require("./images/otherProduct04.png"),
    notFound:require("./images/notFound.png"),
    draghandle:require("./images/drag_handle.png"),
    docoument:require("./images/docoument.png"),
  }
};

export default assets;